"""Initial schema: users table

Revision ID: 2371c9e29b29
Revises:
Create Date: 2025-11-22 05:23:44.490568

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2371c9e29b29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('daily_study_time', sa.Integer(), nullable=True),
    sa.Column('knowledge_level', sa.String(length=50), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('referral_source', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('dark_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dark_mode IN ('light', 'dark', 'auto')", name='check_dark_mode'),
    sa.CheckConstraint("knowledge_level IS NULL OR knowledge_level IN ('Beginner', 'Intermediate', 'Advanced')", name='check_knowledge_level'),
    sa.CheckConstraint("referral_source IS NULL OR referral_source IN ('Search', 'Friend', 'Social', 'Other')", name='check_referral_source'),
    sa.CheckConstraint('target_score IS NULL OR (target_score BETWEEN 0 AND 100)', name='check_target_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
